### ISSUE TITLE
Clone "Docs 0.4.2 Latest" to "Docs 0.5.0 Latest" and make some changes

### ISSUE THREAD

**Issue by lirantal** [meanjs/meanjs.github.io#24]
Since we have mean.js 0.5.0 running on the master branch on the main repo and it embeds quite a few change with it we definitely need to update the docs to add this new section.

Some of the first updates once you clone it are:
- [ ] remove references to grunt, and keep the gulp reference as the main one
- [ ] remove references to the yeoman generator completely and advise on cloning the repo only

cc @danoz-direct

**Comment by miller-productions** [comment]
Thanks @lirantal 

Onto it now.

Question: when you say remove refs to yeoman generator completely, do you also want the top-level Yo Generator page removed?

Screenshot...

![image](https://cloud.githubusercontent.com/assets/15177547/25368638/36bbce34-29c1-11e7-84be-cc3b57842b7d.png)

**Comment by lirantal** [comment]
I think we should because we have no one to maintain it.
Maybe it's too drastic. How about we keep the link there but have a message standing-out on the top of that Yo Generator page above the Overview section saying that the Yeoman Generator is based on an older version of MEAN.JS (0.4.2) and that it's currently unmaintained.

This way we won't also lose all the online documentation on the left-side which might be useful for some people still using the generator on their projects.

and @danoz-direct thanks a lot for picking up the work here, really appreciated!
