### ISSUE TITLE
Changelog page could get long... perhaps link to GitHub release notes instead?

### ISSUE THREAD

**Issue by miller-productions** [meanjs/meanjs.github.io#26]
The [Changelog page](http://meanjs.org/changelog.html) could start to get quite long with the current style of reproducing the release notes. Are we happy for the current style of the Changelog page to remain? Or...

Perhaps we could just link off to the main Releases page and also to the relevant release notes for each release. For example:

- [Releases Home](https://github.com/meanjs/mean/releases)
- [Release 0.5.0](https://github.com/meanjs/mean/releases/tag/0.5.0) 
- [Release 0.4.2](https://github.com/meanjs/mean/releases/tag/v0.4.2) 
- [Release 0.4.1](https://github.com/meanjs/mean/releases/tag/v0.4.1)
- Etc...

What do you think?

_Screenshot for context_

![image](https://cloud.githubusercontent.com/assets/15177547/25369423/1f5c7b5c-29c7-11e7-976c-5ba2a79aea58.png)

**Comment by lirantal** [comment]
I'm generally ok with that page. This way it's easier for someone to quickly find something on the page.

**Comment by miller-productions** [comment]
:ok:
