### ISSUE TITLE
Favicon not working on generated docs/0.*.x pages

### ISSUE THREAD

**Issue by miller-productions** [meanjs/meanjs.github.io#27]
Site is looking for Favicons in the wrong location on the following pages:

- http://meanjs.org/docs/0.4.x/index.html
- http://meanjs.org/docs/0.3.x/index.html

For example, it is trying to serve it from '/docs/0.4x/img/favicon.ico' rather than from '/img/favicon.ico'

**Comment by lirantal** [comment]
Good catch. Waiting for the PR :)
